### ISSUE TITLE
Replace environment constants by dict-like wrapper class

### ISSUE THREAD

**Issue by lkluft** [atmtools/typhon#33]
The current handling of environment variables/configuration does not consider changes in environment variables. This is a direct consequence of the implementation as module **constants**.

I will re-implement the `typhon.environment` module around a dict-like wrapper class (e.g. `os.environ`). Within the `__getitem__` method both, the config and the environment variables will be considered.

### Current implementation
```python
from typhon.environment import ARTS_BUILD_PATH
```

### Future implementation
```python
from typhon.environment import environ

environ['ARTS_BUILDPATH']
```

## To-do list
- [x] Re-implement the `typhon.environment` handling.
- [x] Replace all occurrences of the old constants with a call to `environ`
- [x] Add tests to cover possible clashes properly

Cheers,
Lukas

**Comment by simonpf** [comment]
Can you enlighten me about in which cases this is useful?

As far as I understand environment variables they are bound to processes. So if you run a Python process you would have to kill it anyways to set the environment variables to different values.

And if you want to change these settings from inside Python you can manipulate the attributes directly, thus no need to go through `sys.environ` or IPython magic `%env`.

**Comment by olemke** [comment]
Environment variables are bound to processes, but they're not fixed. You can change them with `os.environ['FOO'] = 'bar'`. Since processes launched from python inherit the new value, the current implementation can lead to inconsistencies. Consider this example:

```
import os
import typhon

print(typhon.environment.ARTS_DATA_PATH)  # Value is /data1 from env variable in this case
print(typhon.arts.run_arts(version=True).stdout)  # ARTS uses /data1 for datapath
os.environ['ARTS_DATA_PATH'] = '/other_data'  # Setting this because I can ;-)
print(typhon.environment.ARTS_DATA_PATH)  # This is still '/data1'
print(typhon.arts.run_arts(version=True).stdout)  # ARTS uses the new env value /other_data
                                                  # _and_ /data1 (passed to ARTS by run_arts)
```

Yes, you can argue to set the Python variable directly. But you would still get an inconsistency here. If you set `arts.environment.ARTS_DATA_PATH`, ARTS would still consider the old /data1 directory because the environment variable still exists with the old value when ARTS is called.
